# gmail.py — Google OAuth flow + Gmail send for FlexyPe Outreach
import os
import base64
import json
import secrets
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime

from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from dotenv import load_dotenv
load_dotenv()

# ─────────────────────────────────────────────
#  CONFIG
# ─────────────────────────────────────────────

CLIENT_ID     = os.getenv("GOOGLE_CLIENT_ID")
CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
REDIRECT_URI  = os.getenv("GOOGLE_REDIRECT_URI", "http://localhost:8080/api/auth/google/callback")
FRONTEND_URL  = os.getenv("FRONTEND_URL", "http://localhost:8080")

SCOPES = [
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.readonly",
]

# In-memory state store: { state_token: flexype_user_email }
# For prod, move to Redis/DB. OK for dev — only used during the OAuth round-trip.
_OAUTH_STATES = {}


def _client_config():
    return {
        "web": {
            "client_id":     CLIENT_ID,
            "client_secret": CLIENT_SECRET,
            "auth_uri":      "https://accounts.google.com/o/oauth2/auth",
            "token_uri":     "https://oauth2.googleapis.com/token",
            "redirect_uris": [REDIRECT_URI],
        }
    }


# ─────────────────────────────────────────────
#  OAUTH FLOW
# ─────────────────────────────────────────────

def build_authorize_url(flexype_user_email: str) -> str:
    """Generate Google OAuth consent URL. Stores user email under a state token."""
    if not CLIENT_ID or not CLIENT_SECRET:
        raise RuntimeError("GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET not configured. See SETUP.md")

    flow = Flow.from_client_config(_client_config(), scopes=SCOPES, redirect_uri=REDIRECT_URI)
    state = secrets.token_urlsafe(24)

    auth_url, _ = flow.authorization_url(
        access_type="offline",        # we need a refresh token
        prompt="consent",             # force refresh-token issuance
        include_granted_scopes="true",
        state=state,
    )
    # Store both the user's email and the PKCE code_verifier generated by the flow
    _OAUTH_STATES[state] = {
        "email": flexype_user_email,
        "code_verifier": flow.code_verifier
    }
    return auth_url


def handle_callback(code: str, state: str, mongo_db) -> dict:
    """Exchange code for tokens, fetch user profile, persist to Mongo."""
    state_data = _OAUTH_STATES.pop(state, None)
    if not state_data:
        raise ValueError("Invalid or expired OAuth state")

    flexype_user_email = state_data["email"]
    code_verifier = state_data["code_verifier"]

    flow = Flow.from_client_config(_client_config(), scopes=SCOPES, redirect_uri=REDIRECT_URI, state=state)
    flow.code_verifier = code_verifier
    flow.fetch_token(code=code)
    creds = flow.credentials

    # Get the Google user profile (email, name)
    oauth2 = build("oauth2", "v2", credentials=creds, cache_discovery=False)
    profile = oauth2.userinfo().get().execute()

    record = {
        "flexype_user":   flexype_user_email,
        "google_email":   profile.get("email"),
        "google_name":    profile.get("name") or profile.get("given_name") or profile.get("email"),
        "google_picture": profile.get("picture"),
        "refresh_token":  creds.refresh_token,
        "scopes":         list(creds.scopes or SCOPES),
        "connected_at":   datetime.utcnow(),
        "updated_at":     datetime.utcnow(),
    }

    mongo_db.gmail_credentials.update_one(
        {"flexype_user": flexype_user_email},
        {"$set": record},
        upsert=True,
    )
    return record


def get_connection_status(flexype_user_email: str, mongo_db) -> dict:
    """Return {connected, google_email, google_name} for the given FlexyPe user."""
    doc = mongo_db.gmail_credentials.find_one({"flexype_user": flexype_user_email})
    if not doc or not doc.get("refresh_token"):
        return {"connected": False}
    return {
        "connected":    True,
        "google_email": doc.get("google_email"),
        "google_name":  doc.get("google_name"),
        "google_picture": doc.get("google_picture"),
        "connected_at": doc.get("connected_at").isoformat() if doc.get("connected_at") else None,
    }


def disconnect(flexype_user_email: str, mongo_db) -> bool:
    res = mongo_db.gmail_credentials.delete_one({"flexype_user": flexype_user_email})
    return res.deleted_count > 0


# ─────────────────────────────────────────────
#  SEND
# ─────────────────────────────────────────────

def _load_credentials(flexype_user_email: str, mongo_db) -> Credentials:
    doc = mongo_db.gmail_credentials.find_one({"flexype_user": flexype_user_email})
    if not doc or not doc.get("refresh_token"):
        raise PermissionError("Gmail is not connected for this user. Connect Gmail first.")

    return Credentials(
        token=None,
        refresh_token=doc["refresh_token"],
        token_uri="https://oauth2.googleapis.com/token",
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        scopes=doc.get("scopes", SCOPES),
    )


def send_email(
    flexype_user_email: str,
    to: str,
    subject: str,
    body: str,
    mongo_db,
    cc: str = "",
    bcc: str = "",
    domain: str = "",
    attachment_data: str = "",
    attachment_name: str = "",
) -> dict:
    """Send email via the logged-in user's Gmail. Logs to Mongo."""
    creds = _load_credentials(flexype_user_email, mongo_db)
    service = build("gmail", "v1", credentials=creds, cache_discovery=False)

    msg = MIMEMultipart("mixed")
    msg["To"] = to
    msg["Subject"] = subject
    if cc:  msg["Cc"]  = cc
    if bcc: msg["Bcc"] = bcc

    # Attach the body text
    msg.attach(MIMEText(body, "plain", "utf-8"))

    # Decode and attach file if provided
    if attachment_data and attachment_name:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(base64.b64decode(attachment_data))
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename=\"{attachment_name}\"",
        )
        msg.attach(part)

    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    try:
        result = service.users().messages().send(userId="me", body={"raw": raw}).execute()
    except HttpError as e:
        # Could be 403 if scope is missing, 401 if revoked.
        raise RuntimeError(f"Gmail send failed: {e}")

    # Log to Mongo
    log_doc = {
        "flexype_user": flexype_user_email,
        "to":           to,
        "cc":           cc,
        "bcc":          bcc,
        "subject":      subject,
        "body":         body,
        "domain":       domain,
        "gmail_message_id": result.get("id"),
        "gmail_thread_id":  result.get("threadId"),
        "sent_at":      datetime.utcnow(),
        "status":       "sent",
        "attachment_name": attachment_name or "",
    }
    mongo_db.sent_emails.insert_one(log_doc)

    return {
        "ok":         True,
        "message_id": result.get("id"),
        "thread_id":  result.get("threadId"),
    }


def list_sent_for_domain(domain: str, mongo_db, limit: int = 20) -> list:
    """Return sent-email log entries for a given merchant domain."""
    cursor = (
        mongo_db.sent_emails
        .find({"domain": domain}, {"_id": 0})
        .sort("sent_at", -1)
        .limit(limit)
    )
    out = []
    for d in cursor:
        if isinstance(d.get("sent_at"), datetime):
            d["sent_at"] = d["sent_at"].isoformat()
        out.append(d)
    return out